### ISSUE TITLE
A back button, or onclick on the background to go back

### ISSUE THREAD

**Issue by SlowLow32** [Devsfy/wiregui#11]
This is more of a feature request
Once you've clicked on a config, you can't go back to the main window without clicking new tunnel then cancel.
![Alt Text](https://i.imgur.com/q2ek4z1.gif)

**Comment by wuzi** [comment]
I don't see much reason to go back to main window, but many people have asked me this because it felt wrong.
I added it on 1.7.

Thanks for suggesting.
