### ISSUE TITLE
[FEATURE REQUEST] MacOS support

### ISSUE THREAD

**Issue by ivan-sirosh** [Devsfy/wiregui#16]
could you please add a build for MacOS?

**Comment by wuzi** [comment]
hey @ivan-sirosh !

added: https://github.com/Devsfy/wiregui/releases/tag/1.8.1

couldn't test it properly, if you find bugs you can open a new issue

**Comment by ivan-sirosh** [comment]
@wuzi - could you please also add x86 pkg?
