### ISSUE TITLE
There is a problem with MacOS

### ISSUE THREAD

**Issue by gwokwong** [Devsfy/wiregui#19]
![image](https://user-images.githubusercontent.com/13887297/170063608-1609eaee-efde-400b-a21d-1a95f64e048c.png)

**Comment by gwokwong** [comment]
Wireguard was not detected on the system

**Comment by zlElo** [comment]
Hi, how do you install WireGUI on your MacOS? WireGUI is a graphical user interface for wireguard (client-side) for linux and windows...

**Comment by wuzi** [comment]
as zlElo mentioned, [wireguard](https://www.wireguard.com/install/) needs to be installed on the system for wiregui to work
