### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by martin0334** [Devsfy/wiregui#23]
wireguard asks for my password with every connection, is there a way to bypass this?
operating system: Linux Mint 21

**Comment by zlElo** [comment]
Not that I know. The program need root rights, and these rights have to accepted with the password. I can advise you that you don't change any permissions or something else :)

Greets

**Comment by guilherme-santos-jscrambler** [comment]
But isn't there a way to make it persistent for a while? Like when you do `sudo <command>` if you try to use sudo again in the next minutes, it won't ask you for the password.

**Comment by zlElo** [comment]
I test it for my Wireguard Linux client and my program need for every connection the root rights too! My program need a authentication for every connection and disconnection.

It's a Linux thing. For every new connection need the program every time the root password. 

I don't know how it's possible to bypass the root rights and is there any way to bypass this.

Greets

**Comment by wuzi** [comment]
yea, unfortunately it's not possible in the current build, wireguard needs sudo permission to run and we used [sudo-prompt](https://github.com/jorangreef/sudo-prompt) to make it run the commands and it does not holds session
