### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by alaikalfaz** [Devsfy/wiregui#25]
how to fix it? I have restarted but the problem is not resolved
![Screenshot from 2022-10-14 06-47-43](https://user-images.githubusercontent.com/61789490/195733471-ca83c912-43c1-4cd7-a156-9397399d3eef.png)

**Comment by zlElo** [comment]
Hello, which version do you have? And which OS do you use? Pleas more informations!

Greets

**Comment by alaikalfaz** [comment]
Sorry in advance for the problems I've uploaded. currently resolved/fixed. the problem arose when I forgot to install wireguard via cli. thanks for such a great tool. I love it. Dikirim dari Galaxy saya
-------- Pesan asli --------Dari: zlElo ***@***.***> Tanggal: 03/12/22  18.54  (GMT+07:00) Ke: Devsfy/wiregui ***@***.***> Cc: phaphaza ***@***.***>, Author ***@***.***> Subjek: Re: [Devsfy/wiregui] how to? (Issue #25) 
Hello, which version do you have? And which OS do you use? Pleas more informations!
Greets

**Comment by zlElo** [comment]
No problem. Please close your issue if your problem is solved :)

Greets

**Comment by zlElo** [comment]
PS: say thanks to wuzi and the other contributors! I only answer :)

**Comment by alaikalfaz** [comment]
Yes Sir Dikirim dari Galaxy saya
-------- Pesan asli --------Dari: zlElo ***@***.***> Tanggal: 03/12/22  19.06  (GMT+07:00) Ke: Devsfy/wiregui ***@***.***> Cc: phaphaza ***@***.***>, Author ***@***.***> Subjek: Re: [Devsfy/wiregui] how to? (Issue #25) 
No problem. Please close your issue if your problem is solved :)
Greets

**Comment by alaikalfaz** [comment]
problem solved flawlessly
