### ISSUE TITLE
Allow user to edit profiles

### ISSUE THREAD

**Issue by RicochetYT** [Devsfy/wiregui#3]
Whenever you import a profile through the menu, the name is set as the filename and you are unable to change it.
It would be very nice if you were able to make it so that you can edit profiles after adding them or importing them, whether that be changing name or anything about it.

Thanks for the project! It looks very nice, especially compared to QOMUI.

**Comment by wuzi** [comment]
Hey @RicochetYT !

What a surprise someone already found this project.

It should let you edit the name while adding a new profile, might be a bug.

I also miss the ability to update the name after the profile is added, I'll probably play with it later today.

Thanks, glad you liked it.

**Comment by RicochetYT** [comment]
> Hey @RicochetYT !

Heya Wuzi!

> What a surprise someone already found this project.

Was hoping to find a new Wireguard GUI, QOMUI is outdated and buggy. This looked nice.

> It should let you edit the name while adding a new profile, might be a bug.

When you import a profile from a file, it ignored whatever name I typed, unless I missed something, it'll instead use the filename as the name.

> I also miss the ability to update the name after the profile is added, I'll probably play with it later today.

Sounds sweet!

> Thanks, glad you liked it.

No problem! I thought this project looked nice and it was new, just needed something a bit more up-to-date and reliable than QOMUI.
