### ISSUE TITLE
can not install wiregui on ubuntu22.04

### ISSUE THREAD

**Issue by spereg53** [Devsfy/wiregui#30]
dpkg: dependency problems prevent configuration of wiregui:
 wiregui depends on libgtk-3-0; however:
  Package libgtk-3-0 is not installed.
 wiregui depends on libnotify4; however:
  Package libnotify4 is not installed.
 wiregui depends on libxtst6; however:
  Package libxtst6 is not installed.
 wiregui depends on xdg-utils; however:
  Package xdg-utils is not installed.
 wiregui depends on libatspi2.0-0; however:
  Package libatspi2.0-0 is not installed.
 wiregui depends on libgbm1; however:
  Package libgbm1 is not installed.
 wiregui depends on libxcb-dri3-0; however:
  Package libxcb-dri3-0 is not installed.

can you help me,thanks

**Comment by spereg53** [comment]
the problem is because ubuntu 22.04 was installed lite mode not graphical

**Comment by ghost** [comment]
> the problem is because ubuntu 22.04 was installed lite mode not graphical

thanks
