### ISSUE TITLE
User did not grant permission 

### ISSUE THREAD

**Issue by SlowLow32** [Devsfy/wiregui#8]
I keep getting "User did not grant permission" trying to connect to a VPN. Running as admin did not solve the problem.
![image](https://user-images.githubusercontent.com/87282255/125209448-bf71b400-e290-11eb-9445-8b9dcfca41bd.png)

**Comment by wuzi** [comment]
That error usually occurs when the password is not provided for sudo-prompt.

Does it open the prompt box asking for the sudo/admin password?

Which OS are you running?

**Comment by SlowLow32** [comment]
> That error usually occurs when the password is not provided for sudo-prompt.
> 
> Does it open the prompt box asking for the sudo/admin password?
> 
> Which OS are you running?

Running windows 10, it does not open a prompt from installation to trying to connect. 
I'm assuming that error should pop up to Linux users right?

**Comment by wuzi** [comment]
It should display a window asking for the admin password when activating the connection, if the user doesn't provide it will pop up that error.

The latest versions I did not test on windows, I'll try it on my PC to see if I can reproduce it.

**Comment by SlowLow32** [comment]
> It should display a window asking for the admin password when activating the connection, if the user doesn't provide it will pop up that error.
> 
> The latest versions I did not test on windows, I'll try it on my PC to see if I can reproduce it.

I tested the first version on a windows 10 sandbox and it worked fine. I then uninstalled it then installed 1.6 but it didn't work, gave a new error.
![image](https://user-images.githubusercontent.com/87282255/125211741-6447bd80-e2a0-11eb-874c-e3aa6d5bd9e1.png)
I then uninstalled 1.6 then installed every version after 1.0 (the ones where it had an exe to download from the release) and test it to see if it worked and it did, even 1.6 worked. But I created a new Windows 10 sandbox and started with 1.6 again and it gave the error in the above picture. It seems that by going through each update 1.6 will work, but if you're on a fresh pc and start at 1.6 then it will not. I'm guessing when you uninstall the program it doesn't completely remove everything but leaves something that makes 1.6 works.

**Comment by wuzi** [comment]
> > It should display a window asking for the admin password when activating the connection, if the user doesn't provide it will pop up that error.
> > The latest versions I did not test on windows, I'll try it on my PC to see if I can reproduce it.
> 
> I tested the first version on a windows 10 sandbox and it worked fine. I then uninstalled it then installed 1.6 but it didn't work, gave a new error.
> ![image](https://user-images.githubusercontent.com/87282255/125211741-6447bd80-e2a0-11eb-874c-e3aa6d5bd9e1.png)
> I then uninstalled 1.6 then installed every version after 1.0 (the ones where it had an exe to download from the release) and test it to see if it worked and it did, even 1.6 worked. But I created a new Windows 10 sandbox and started with 1.6 again and it gave the error in the above picture. It seems that by going through each update 1.6 will work, but if you're on a fresh pc and start at 1.6 then it will not. I'm guessing when you uninstall the program it doesn't completely remove everything but leaves something that makes 1.6 works.

Thanks for the detailed report!

I couldn't reproduce the error when doing a quick test installing 1.6 in a new sandbox (Windows 10), I'll try again later. If possible, try it again, it could happen when closing the confirmation window quickly.

Somewhere during the versions I did actually change the path from `Wire GUI` to `wiregui`, but that shouldn't cause this since it creates the folder in `%appdata%` during installation.

About that new error, that could be caused by a different version in wireguard/wg-quick, I guess you didn't install wireguard in the new VM? (there's a notification telling that wireguard is not installed when initializing the app, but it is very easy to miss).

**Comment by SlowLow32** [comment]
The first bug I can reproduce every time on my local machine but not sandbox. Probably got some stuff I've installed that is causing the conflict and showing "User did not grant permission".
The second bug can be reproduced on a sandbox or mine at least.
I installed wireguard then installed the latest version of wiregui.
https://youtu.be/wCTziOnQxIY

**Comment by SlowLow32** [comment]
I've tested it on a new windows installation and came to the conclusion that the first bug was due to conflicts with other programs (couldn't find which one). The second bug seems only seems reproducible on windows sandbox.

**Comment by wuzi** [comment]
> I've tested it on a new windows installation and came to the conclusion that the first bug was due to conflicts with other programs (couldn't find which one). The second bug seems only seems reproducible on windows sandbox.

Nice!

The second happened to me once, I'll add a better error message when that happens.

**Comment by wuzi** [comment]
Thanks for the effort in reporting this.
